version: '3'
services:
  #Postgres para armazenamento das informações de precificação
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: laurinha!2
      POSTGRES_DB: precificacao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #Redis para processamento das informações 
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data

volumes:
  postgres-data:
  redis-data:


