version: '3'
services:
#  app:
#    image: openjdk:17.0.1-jdk-slim
#    command: bash -c 'cd tmp && mvn spring-boot:run'
#    volumes:
#      - .:/tmp
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: laurinha!2
      POSTGRES_DB: precificacao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: